version: "2"

run:
  timeout: 10m
  # Режим загрузки модулей: vendor (если используется vendor каталог) или mod (по умолчанию)
  # Если vendor каталог не используется, можно закомментировать эту строку
  # modules-download-mode: vendor

# Форматеры - инструменты для автоматического форматирования кода
# Больше информации: https://golangci-lint.run/docs/formatters/
formatters:
  enable:
    # Форматирует код и импорты с дополнительными правилами (строже чем gofmt)
    - gofumpt
    # Управляет порядком и группировкой импортов
    - gci
    # Исправляет длинные строки (опционально, может конфликтовать с lll линтером)
    # - golines

  settings:
    gofumpt:
      # Дополнительные правила форматирования
      extra-rules: true
      # Форматирование строк в стиле Go 1.19+
      lang-version: "1.25"
    gci:
      # Секции импортов: standard, default, prefix, blank, dot
      sections:
        - standard  # Стандартная библиотека Go
        - default   # Все остальные импорты
        - prefix(github.com/art-injener/satwatch-go)  # Локальные импорты проекта
      # Пользовательский порядок секций
      custom-order: true
      # Не добавлять пустые строки между секциями одного типа
      skip-generated: true
    # golines:
    #   # Максимальная длина строки (должна соответствовать lll.line-length)
    #   max-len: 160
    #   # Минимальная длина строки для разбиения
    #   tab-len: 1

# Больше информации https://golangci-lint.run/usage/linters/
linters:
  # В версии 2: default может быть "all", "standard", "none" или "fast"
  # Используем "none" и явно включаем нужные линтеры
  default: none
  enable:
    # Вычисляет и проверяет цикломатическую сложность функций
    - gocyclo
    # Проверяет, использует ли функция не унаследованный контекст
    - contextcheck
    # Проверяет, успешно ли закрыто тело HTTP-ответа
    - bodyclose
    # Проверяет исходный код Go и сообщает о подозрительных конструкциях, таких как вызовы Printf, аргументы которых не совпадают со строкой формата
    - govet
    # Обнаруживает непроверенные ошибки в программах Go
    - errcheck
    # Определяет код, который вызовет проблемы со схемой переноса ошибок, введенной в Go 1.13
    - errorlint
    # Это набор правил от staticcheck
    - staticcheck
    # Проверяет код Go на наличие неиспользуемых констант, переменных, функций и типов
    - unused
    # Определяет, когда назначения существующим переменным не используются
    - ineffassign
    # Замена golint.
    - revive
    # Проверяет исходный код на наличие проблем безопасности, РЕКОМЕНДУЕТСЯ КАСТОМНАЯ НАСТРОЙКА ПОД КОНКРЕТНЫЙ ПРОЕКТ
    - gosec
    # Удаляет ненужные преобразования типов
    - unconvert
    # Обнаруживает дублирование кода
    - dupl
    # Находит повторяющиеся строки, которые могут быть заменены константой
    - goconst
    # Проверяет корректность использования директив nolint
    - nolintlint
    # Находит часто встречающиеся английские слова с ошибками в комментариях
    - misspell
    # Сообщает о длинных строках
    - lll
    # Сообщает о неиспользуемых параметрах функции
    - unparam
    # Проверяет назначения со слишком большим количеством пустых идентификаторов
    - dogsled
    # Находит голые возвраты в функциях, превышающих заданную длину функции
    - nakedret
    # Находит объявления срезов, для которых потенциально можно выделить память
    - prealloc
    # Предоставляет диагностику, которая проверяет наличие ошибок, проблем с производительностью и стилем.
    # Расширяемый без перекомпиляции с помощью динамических правил.
    # Динамические правила написаны декларативно с использованием шаблонов AST, фильтров, сообщений отчета и необязательных предложений.
    - gocritic
    # Проверяет, что в коде Go отсутствуют функции инициализации
    - gochecknoinits
    # Обнаруживает начальные и завершающие пробелы
    - whitespace
    # Обнаруживает длинные функции, РЕКОМЕНДУЕТСЯ НАСТРАИВАТЬ ПОД ПРОЕКТ
    - funlen
    # Проверяет, что функции, подобные printf, называются с помощью f в конце
    - goprintffuncname
    # Обнаруживает места, где переменные цикла копируются (замена exportloopref в v2)
    - copyloopvar
    # Делает отчеты о глубоко вложенных операторах if
    - nestif
    # Проверяет наличие двух временных значений, умноженных вместе
    #    func waitForSeconds(someDuration time.Duration) {
    #    timeToWait := someDuration * time.Second
    #    fmt.Printf("Waiting for %s\n", timeToWait)
    #  }
    #
    #  func main() {
    #  waitForSeconds(5) // waits for 5 seconds
    #  waitForSeconds(5 * time.Second) // waits for 1388888h 53m 20s
    #  }
    - durationcheck
    # Проверяет, что контрольные ошибки имеют префикс Err, а типы ошибок имеют суффикс Error
    - errname
    # Проверяет исчерпываемость инструкций enum switch и литералов сопоставления
    - exhaustive
    # Находит объявления срезов с ненулевой начальной длиной
    - makezero
    # Находит код, который возвращает nil, даже если он проверяет, что ошибка не равна нулю, РЕКОМЕНДУЕТСЯ НАСТРОИТЬ ПОД ПРОЕКТ
    - nilerr
    # Проверяет, что нет одновременного возврата ошибки nil и недопустимого значения
    - nilnil
    # Обнаруживает возможность использования переменных / констант из стандартной библиотеки Go
    - usestdlibvars
    # Проверяет, что sql.Rows, sql.Stmt закрыты (важно для работы с БД)
    - sqlclosecheck
    # Проверяет, что Rows.Err проверяется после итерации по результатам SQL
    - rowserrcheck
    # Проверяет правильную обработку ошибок (автофикс)
    - err113
    # Обнаруживает вложенные контексты в циклах (автофикс)
    - fatcontext
    # Находит fmt.Sprintf, которые можно заменить на более быстрые альтернативы (автофикс)
    - perfsprint
    # Находит бесполезные присваивания
    - wastedassign
    # Предлагает использовать integer range в циклах для Go 1.22+ (автофикс)
    - intrange
    # Находит неправильное использование bytes/strings (автофикс)
    - mirror
    # Проверяет точки в конце комментариев (автофикс)
    - godot
    # Проверяет исчерпывающность для "sum types"
    - gochecksumtype
    # Предлагает упрощения с использованием современных возможностей Go
    - modernize
    # Находит функции из golang.org/x/exp/, которые можно заменить стандартными (автофикс)
    - exptostd
    # Проверяет использование log/slog на соответствие стилю
    - sloglint
    # Проверяет, что нет пропущенных вызовов t.Helper() в тестовых хелперах
    - thelper
    # Проверяет выравнивание тегов структур (автофикс)
    - tagalign

  # В версии 2 настройки линтеров находятся в linters.settings
  settings:
    gocyclo:
      # Минимальная сложность кода для сработки. По-умолчанию 30, но рекомендуется 10-20
      min-complexity: 20
    gosec:
      # Исключить правила (более подробно https://golangci-lint.run/usage/linters/#gosec)
      excludes:
        # Ошибки аудита не проверены
        - G104
        # URL-адрес, предоставленный HTTP-запросу в качестве входных данных для заражения
        - G107
        # Небезопасный источник случайных чисел (rand)
        - G404
        # Неявное наложение псевдонимов в памяти элементов из инструкции range
        - G601
    funlen:
      # Минимальное количество строк функции для срабатывания проверки
      lines: 150
      # Минимальное количество операторов функции для срабатывания проверки
      statements: 80
    errcheck:
      # Отчет о присвоении ошибок пустому идентификатору: `num, _ := strconv.Atoi(numStr)`
      check-blank: true
    lll:
      # Ширина табуляции в пробелах
      tab-width: 4
      # Длина строки для сработки проверки
      line-length: 160
    revive:
      rules:
        # Предупреждает, когда не соблюдаются соглашения об именовании инициализатора, переменных или пакетов
        - name: var-naming
          arguments: [ [ "ID", "UID", "UUID", "URL", "IP", "API", "HTTP" ], [ ] ]
    misspell:
      # Исправьте написание, используя языковые настройки для США или Великобритании.
      # Установка локали в US исправит британское написание слова "color" на "color".
      # По умолчанию используется нейтральная разновидность английского языка
      locale: US
    nestif:
      # Минимальная сложность операторов if
      min-complexity: 4
    # staticcheck:
    #   # Версия Go для staticcheck. Если не указано, используется версия из go.mod
    #   # Раскомментируйте и укажите версию, если нужно явно задать версию Go для staticcheck
    #   # go: "1.25"
    dupl:
      # Минимальное количество дублированных символов
      threshold: 100
    goconst:
      # Искать среди чисел
      numbers: true
      # Минимальное значение повторений, работает только с goconst.numbers
      min: 3
      # Игнорировать, когда константа не используется в качестве аргумента функции
      ignore-calls: false
    nolintlint:
      # Требовать объяснение для директив nolint
      require-explanation: true
      # Требовать указания конкретного линтера в nolint
      require-specific: true
    godot:
      # Проверять только экспортируемые декларации (более мягкая настройка)
      scope: declarations
      # Исключить из проверки определенные комментарии
      exclude:
        - "^TODO:"
        - "^FIXME:"
        - "^NOTE:"
      # Разрешить комментарии без заглавной буквы
      capital: false
    sloglint:
      # Запретить смешивание key-value аргументов и атрибутов
      no-mixed-args: true
      # Требовать использование статических значений для ключей
      key-naming-case: snake
    tagalign:
      # Выравнивать теги структур
      align: true
      # Сортировать теги
      sort: true
    perfsprint:
      # Проверять все форматы, включая int-to-string
      int-conversion: true
      err-error: true
      errorf: true
      sprintf1: true

  # В версии 2 исключения настраиваются через linters.exclusions
  exclusions:
    # Исключить запуск некоторых линтеров в тестовых файлах
    rules:
      - path: _test\.go
        linters:
          - gosec
          - funlen
          - gocyclo
          - err113
          - errcheck  # В тестах допустимо игнорировать некоторые ошибки
          - goconst   # В тестах допустимы повторяющиеся строки
          - gci       # Форматирование импортов в тестах менее критично

issues:
  # Максимальное количество задач на один линтер. Установите 0, чтобы отключить. По умолчанию 50
  max-issues-per-linter: 0

  # Максимальное количество задач с одинаковым текстом. Установите 0, чтобы отключить. По умолчанию 3
  max-same-issues: 0
